movehelper/forms/tasks.py
from flask_ckeditor import CKEditorField
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField, ValidationError, HiddenField, BooleanField, PasswordField
from wtforms.validators import DataRequired, Email, Length, Optional, URL
from movehelper.models import UserTasks


class NewTask(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(1, 60)])
    context = CKEditorField('Context', validators=[DataRequired()])
    contact = StringField('Contact', validators=[DataRequired()])
    location = StringField('Location', validators=[DataRequired()])
    manpower = SelectField('Manpower Requirement', choices=(("1","1"),("2","2"),("3","3")), validators=[DataRequired()])
    submit = SubmitField()

movehelper/blueprints/tasks.py
from flask import render_template, flash, redirect, url_for, Blueprint, request, current_app
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login
from datetime import datetime
from sqlalchemy import join


from movehelper.config import Operations
from movehelper.emails import send_confirm_email
from movehelper.forms.tasks import NewTask
from movehelper.models import UserAccount, UserTasks, TaskOrders
from movehelper.tools import db
from movehelper.helpers import generate_token, validate_token
from movehelper.filter import confirm_required


tasks_bp = Blueprint('tasks', __name__)


@tasks_bp.route('/opentasks')
@login_required
def opentasks():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOVEHELPER_TASKS_PER_PAGE']
    pagination = UserTasks.query.filter(UserTasks.user_id!=current_user.id, UserTasks.status==False).order_by(UserTasks.pubtime.desc()).paginate(page, per_page=per_page)
    tasks = pagination.items
    return render_template('tasks/opentasks.html', pagination=pagination, tasks=tasks)


@tasks_bp.route('/new', methods=['GET', 'POST'])
@login_required
@confirm_required
def newtask():
    form = NewTask()
    if form.validate_on_submit():
        title = form.title.data
        context = form.context.data
        contact = form.contact.data
        location = form.location.data
        mpnum = form.manpower.data
        task = UserTasks(title=title, context=context, contact=contact, location=location, mpnum=mpnum, user_id=current_user.id )
        db.session.add(task)
        db.session.commit()
        flash('Task Created!', 'success')
        return redirect(url_for('user.index'))
    return render_template('tasks/newtask.html', form=form)

    
@tasks_bp.route('task/<int:task_id>', methods=['GET', 'POST'])
@login_required
@confirm_required
def taskdet(task_id):
    task = UserTasks.query.get_or_404(task_id)
    orders = TaskOrders.query.filter(TaskOrders.task_id==task_id).all()
    order = TaskOrders.query.filter(TaskOrders.task_id==task_id, TaskOrders.manpower==current_user.id).all()
    taskstatus = task.status
    return render_template('tasks/taskdet.html', task=task, taskstatus=taskstatus, orders=orders, order=order)
    

@tasks_bp.route('/mytasks', methods=['GET', 'POST'])
@login_required
@confirm_required
def mytasks():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOVEHELPER_TASKS_PER_PAGE']
    pagination = UserTasks.query.filter(UserTasks.user_id==current_user.id).order_by(UserTasks.pubtime.desc()).paginate(page, per_page=per_page)
    usertasks = pagination.items
    return render_template('tasks/mytasks.html', pagination=pagination, usertasks=usertasks)


@tasks_bp.route('/task/<int:task_id>/taskedit', methods=['GET', 'POST'])
@login_required
@confirm_required
def taskedit(task_id):
    form = NewTask()
    task = UserTasks.query.get_or_404(task_id)
    if form.validate_on_submit():
        task.title = form.title.data
        task.context = form.context.data
        task.contact = form.contact.data
        task.location = form.location.data
        task.mpnum = form.manpower.data
        db.session.commit()
        flash('Task Updated!','success')
        return redirect(url_for('tasks.taskdet', task_id=task.id))
    form.title.data = task.title
    form.context.data = task.context
    form.contact.data = task.contact
    form.location.data = task.location
    return render_template('tasks/taskedit.html', form=form, task=task)


@tasks_bp.route('/task/<int:task_id>/taskdelete', methods=['GET', 'POST'])
@login_required
@confirm_required
def taskdelete(task_id):
    task = UserTasks.query.get_or_404(task_id)
    db.session.delete(task)
    db.session.commit()
    flash ('Task Deleted!', 'success')
    return redirect(url_for('tasks.mytasks'))


@tasks_bp.route('/task/<int:task_id>/applieddet', methods=['GET', 'POST'])
@login_required
@confirm_required
def applieddet(task_id):
    task = UserTasks.query.get_or_404(task_id)
    applyers = TaskOrders.query.join(UserAccount, TaskOrders.manpower==UserAccount.id).\
            filter(TaskOrders.task_id==task_id).with_entities(TaskOrders.id, TaskOrders.createtime, UserAccount.fname,\
            UserAccount.mname, UserAccount.lname, UserAccount.gender, UserAccount.birth, UserAccount.onid, UserAccount.license)\
            .all()
    return render_template('tasks/orderdet.html', task=task, applyers=applyers)

movehelper/blueprints/user.py
from flask import flash, redirect, url_for, render_template, Blueprint, request, current_app
from flask_login import login_user, logout_user, login_required, current_user, login_fresh
from sqlalchemy import or_

from movehelper.emails import send_order_email, send_order_email_2
from movehelper.forms.user import Certification, PasswordChange
from movehelper.models import UserAccount, UserTasks, TaskOrders
from movehelper.tools import db
from movehelper.filter import confirm_required, certificate_required


user_bp = Blueprint('user', '__name__')


@user_bp.route('/')
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOVEHELPER_TASKS_PER_PAGE']
    pagination = UserTasks.query.filter(UserTasks.user_id!=current_user.id).order_by(UserTasks.pubtime.desc()).paginate(page, per_page=per_page)
    tasks = pagination.items
    return render_template('user/index.html', pagination=pagination, tasks=tasks)


@user_bp.route('/passwordchange', methods=['GET', 'POST'])
@login_required
def passwordchange():
    form = PasswordChange()
    if form.validate_on_submit():
        current_user.create_password(form.pwd.data)
        db.session.commit()
        flash('PasswordChange successed. Please re-Login', 'success')
        logout_user()
        return redirect(url_for('main.index'))
    return render_template('user/passwordchange.html', form=form)


@user_bp.route('/certificate', methods=['GET', 'POST'])
@login_required
@confirm_required
def certificate():
    user = UserAccount.query.get_or_404(current_user.id)
    if user.certificated == True :
        flash('You were already certificated!', 'warning')
        return redirect(url_for('user.index'))
    else :
        form = Certification()
        if form.validate_on_submit():
            current_user.fname = form.namef.data
            current_user.mname = form.namem.data
            current_user.lname = form.namel.data
            current_user.birth = form.birthday.data
            current_user.gender = form.gender.data
            current_user.phone = form.phone.data
            current_user.onid = form.onid.data
            current_user.license = form.license.data
            current_user.certificated = True
            db.session.commit()
            flash('Certification successed.', 'success')
            return redirect(url_for('user.index'))
        return render_template('user/certificate.html', form = form)


@user_bp.route('/applytask/<int:task_id>', methods=['GET', 'POST'])
@login_required
@confirm_required
@certificate_required
def applytask(task_id):
    task = UserTasks.query.get_or_404(task_id)
    if  task.status == False:
        if task.mpnume < (task.mpnum - 1): 
            neworder = TaskOrders(manpower=current_user.id, task_id=task_id)
            task.mpnume += 1
            db.session.add(neworder)
            db.session.commit()
            flash('You applied this task', 'success')
            return redirect(url_for('user.index'))
        else:
            neworder = TaskOrders(manpower=current_user.id, task_id=task_id)
            task.mpnume += 1
            task.status = True
            db.session.add(neworder)
            db.session.commit()
            announcer = UserAccount.query.get_or_404(task.user_id)
            applyers = TaskOrders.query.join(UserAccount, TaskOrders.manpower==UserAccount.id).\
                        filter(TaskOrders.task_id==task_id).with_entities(UserAccount.email,\
                        UserAccount.username).all()
            send_order_email(announcer=announcer, taskNo=task_id)
            send_order_email_2(applyers=applyers, taskNo=task_id)
            flash('You applied this task', 'success')
            return redirect(url_for('user.index'))
    else :  
        flash('This task was closed', 'warning')
        return redirect(url_for('tasks.taskdet', task_id=task.id))


@user_bp.route('/myapply', methods=['GET', 'POST'])
@login_required
@confirm_required
@certificate_required
def myapply():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOVEHELPER_TASKS_PER_PAGE']
    pagination = UserTasks.query.join(TaskOrders).filter(TaskOrders.manpower==current_user.id).with_entities(TaskOrders.id, TaskOrders.task_id, UserTasks.title, TaskOrders.createtime).order_by(TaskOrders.createtime.desc()).paginate(page, per_page=per_page)
    applys = pagination.items
    return render_template('user/myapplys.html', pagination=pagination, applys=applys)

movehelper/templates/tasks/mytasks.html
{% extends 'base2.html' %}
{% from 'bootstrap/pagination.html' import render_pager %}
{% block content %}
<style>
    /* unvisited link */
    .mtask a:link {
    color: white;
    text-decoration:none;
    }

    /* visited link */
    .mtask a:visited {
    color: white;
    text-decoration:none;
    }

    /* mouse over link */
    .mtask a:hover {
    color: white;
    text-decoration:none;
    }

    /* selected link */
    .mtask a:active {
    color: white;
    text-decoration:none;
    }

    h4{
    margin: 20px;
    }

    .button1:link, .button1:visited {   
        background-color: #474542;
        color: white;
        padding: 14px 25px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        margin-left: 10px;
        margin-top: 10px;
        font-weight: bold;
        font-family: "Times New Roman", Times, serif;
        border-radius: 8px;
    }

        .button1:hover, .button1:active {
        color: black;
        background-color: rgb(50, 90, 85);
    }

</style>
    <h1>MoveHelper </h1>
    <h2>{{ current_user.username }}'s Tasks</h2>
        <div class="row">
            <div class="col-sm-8">
                
                {% if usertasks %}
                    {% for usertask in usertasks %}
                    <P nowrap>
                        <p style="display: inline;">TaskNO.&nbsp;{{ usertask.id }}&nbsp;&nbsp;|&nbsp;&nbsp;Title:&nbsp;&nbsp;{{ usertask.title }}&nbsp;&nbsp;|&nbsp;&nbsp;Released at:&nbsp;&nbsp;{{ usertask.pubtime }}</p>&nbsp;&nbsp;
                        {% if usertask.status == False %}
                            <form class="mtask" method="POST" style="display: inline;">
                                <button type="submit" class="btn btn-info btn-sm" style="background-color: chartreuse; white-space: nowrap;" formaction="{{ url_for('tasks.taskdet', task_id=usertask.id) }}">Unapplied</button>&nbsp;
                                <button type="submit" class="btn btn-info btn-sm"><a style="color: cornsilk;" href="{{ url_for('tasks.taskedit', task_id=usertask.id) }}">Edit this Task</a></button>&nbsp;
                                <button type="submit" class="btn btn-info btn-sm" onclick="return confirm('Are you sure?');" formaction="{{ url_for('tasks.taskdelete', task_id=usertask.id) }}">Delete this Task</button>
                            </form>
                        {% else %}
                            <form method="POST" style="display: inline;">
                                <button class="btn btn-info btn-sm" style="background-color: rgb(245, 16, 27); white-space: nowrap;" formaction="{{ url_for('tasks.applieddet', task_id=usertask.id) }}">Applied</button>&nbsp;
                            </form>
                        {% endif %}
                    </P>
                    {% endfor %}
                    {% if usertasks %}
                        <div class="page-footer">{{ render_pager(pagination) }}</div>
                    {% endif %}
                {% else %}    
                    <h4>No records!</h4>
                {% endif %}
            </div>
        </div>
        <a class="button1" href="{{ url_for('tasks.newtask') }}">Release Task</a></br>
        <a class="button1" href="{{ url_for('user.index') }}">Back to My Home</a>
{% endblock %}

movehelper/templates/tasks/newtask.html
{% extends 'base2.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}NewTask{% endblock %}

{% block content %}
<style>
    body{
            background-image: url("https://prd-image-masters.caravan-stories.com.tw/c/sig=1.wJPHhERFgwnK6pqXcpnOuTgK_Pkdv2HcqqPh335P2iM=/caravan-stories/masters/production-tw/attachments/1b21c7fb435b583e0592c03c04df26a9.jpg");
            background-repeat: no-repeat;
            background-size: cover;       
    }


    .button2:link, .button2:visited {   
        background-color: #474542;
        color: white;
        padding: 14px 25px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        margin-left: 10px;
        margin-top: 10px;
        font-weight: bold;
        font-family: "Times New Roman", Times, serif;
        border-radius: 8px;
    }

    .button2:hover, .button2:active {
        color: black;
        background-color: rgb(50, 90, 85);
    }


</style>

    <div class="jumbotron">
        <div class="row">
           
            <div class="col-md-4">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header"><h4>Release New Task!</h4></div>
                    <div class="card-body">
                        {{ render_form(form) }}
                        <hr>
                        
                    </div>
                    </div>
                </div>
            </div>
            <a class="button2"    href="{{ url_for('tasks.mytasks') }}">Back to My Tasks</a>
    </div>
{% endblock %}

movehelper/templates/tasks/opentasks.html
{% extends 'base2.html' %}
{% from 'bootstrap/pagination.html' import render_pager %}
{% block content %}
<style>
.button1:link, .button1:visited {   
        background-color: #b1d825;
        color: rgb(129, 73, 8);
        padding: 14px 25px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        margin-left: 10px;
        margin-top: 10px;
        font-weight: bold;
        font-family: "Times New Roman", Times, serif;
        border-radius: 8px;
    }

        .button1:hover, .button1:active {
        color: black;
        background-color: rgb(50, 90, 85);
    }

</style>



    <h1>MoveHelper </h1>
        <div class="row">
            <div class="col-sm-8">
                
                {% if tasks %}
                    {% for task in tasks %}
                        <P>
                            <p style="display: inline;">&nbsp;&nbsp;{{ task.title }}&nbsp;&nbsp;|&nbsp;&nbsp;Released at:&nbsp;&nbsp;{{ task.pubtime }}</p>&nbsp;&nbsp;
                            <form method="POST" style="display: inline;">
                                <button type="submit" class="btn btn-info btn-sm" style="background-color: chartreuse; white-space: nowrap;" formaction="{{ url_for('tasks.taskdet', task_id=task.id) }}">Apply Now</button>&nbsp;
                            </form>
                        </P>
                    {% endfor %}
                    {% if tasks %}
                        <div class="page-footer">{{ render_pager(pagination) }}</div>
                    {% endif %}
                {% else %}    
                    <h4>No open tasks, please waitting!</h4>
                {% endif %}
            </div>
        </div>
        <a class="button1" href="{{ url_for('user.index') }}">Back to My Home</a></br>
        <a class="button1" href="{{ url_for('user.myapply') }}">Back to My Applied Tasks</a>
{% endblock %}

movehelper/templates/tasks/orderdet.html
{% extends 'base2.html' %}
    
{% block content %}
<style>
   


</style>

    <h1>MoveHelper </h1>
    <div class="row">
        <div class="col-sm-8">
            <P>Task Details</P>
            <p>Title:&nbsp;&nbsp;{{ task.title }}</p>
            <p>Context:&nbsp;&nbsp;{{ task.context }}</p>
            <p>Contact:&nbsp;&nbsp;{{ task.contact }}</p>
            <p>Location:&nbsp;&nbsp;{{ task.location }}</p>
        </div>
        {% for applyer in applyers %}
            <div class="col-sm-8">
                <p>Application Details</p>
                <p>OrderID:&nbsp;&nbsp;{{ applyer.id }}</p>
                <p>Applied DateTime:&nbsp;&nbsp;{{ applyer.createtime }}</p>
                <p>Name:&nbsp;&nbsp;{{ applyer.fname }}.{{ applyer.mname }}.{{ applyer.lname }}</p>
                <p>Gender:&nbsp;&nbsp;{{ applyer.gender }}</p>
                <p>Birthday:&nbsp;&nbsp;{{ applyer.birth }}</p>
                <p>ONID:&nbsp;&nbsp;{{ applyer.onid }}</p>
                <p>Driver Lisence:&nbsp;&nbsp;{{ applyer.license }}</p>
            </div>
        {% endfor %}
    </div>
    
    <a href="{{ url_for('tasks.mytasks') }}">Back to My Tasks</a>

{% endblock %}

movehelper/templates/tasks/taskdet.html
{% extends 'base2.html' %}
    
{% block content %}
<style>
.button1:link, .button1:visited {   
        background-color: #474542;
        color: white;
        padding: 14px 25px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        margin-left: 10px;
        margin-top: 10px;
        font-weight: bold;
        font-family: "Times New Roman", Times, serif;
        border-radius: 8px;
    }

    .button1:hover, .button1:active {
        color: black;
        background-color: rgb(50, 90, 85);
    }


</style>
    <h1>MoveHelper </h1>
    <div class="row">
        <div class="col-sm-8">
            {% if taskstatus == False %}
                <p style="color: green;">Task Status: Task is waiting to apply!</p>
            {% else %}
                <p style="color: red;">Task Status: Task Was Closed</p>
            {% endif %}
            <p>Title:&nbsp;&nbsp;{{ task.title }}</p>
            <p>Announcer:&nbsp;&nbsp;{{ task.ua.username }}</p>
            <p>Release Time:&nbsp;&nbsp;{{ task.pubtime }}</p>
            <p>Context:&nbsp;&nbsp;{{ task.context }}</p>
            <p>Contact:&nbsp;&nbsp;{{ task.contact }}</p>
            <p>Location:&nbsp;&nbsp;{{ task.location }}</p>
            <p>Manpower Requirement:&nbsp;&nbsp;{{ task.mpnum }}</p>
            {% if task.mpnume == 0 %}
                <p style="color: green;">Appiled person:&nbsp;&nbsp;{{ task.mpnume }}</p>
            {% elif task.mpnume < task.mpnum %}
                <p style="color: goldenrod;">Appiled person:&nbsp;&nbsp;{{ task.mpnume }}</p>
            {% elif task.mpnume == task.mpnum %}
                <p style="color: red;">Appiled person:&nbsp;&nbsp;{{ task.mpnume }}</p>
            {% endif %}
        </div>
    </div>
    {% if orders %}
        {% if order %}
            {% if current_user.id == task.user_id and task.mpnume != 0%}
                <p style="color: coral;">Your task was appiled, you can not eidt or delete it!</p>
            {% elif current_user.id != task.user_id and taskstatus == False %}
                <p style="color: blueviolet;">You were already appiled this task.</p></br></br>                
            {% endif %}
        {% else %}
            {% if current_user.id == task.user_id and task.mpnume != 0%}
                <p style="color: coral;">Your task was appiled, you can not eidt or delete it!</p>
            {% elif current_user.id != task.user_id and taskstatus == False %}
                <a class="btn btn-info btn-sm" style="background-color: blueviolet;" onclick="return confirm('Are you sure?');" href="{{ url_for('user.applytask', task_id=task.id) }}">Apply Task</a></br></br>
            {% endif %}
        {% endif %}
    {% else %}
        {% if current_user.id == task.user_id and taskstatus == False and task.mpnume == 0 %}
            <a class="btn btn-info btn-sm" href="{{ url_for('tasks.taskedit', task_id=task.id) }}">Edit this Task</a></br></br>   
            <form class="inline" method="post"
                action="{{  url_for('tasks.taskdelete', task_id=task.id) }}">
                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">Delete</button>
            </form></br></br>
        {% elif current_user.id != task.user_id and taskstatus == False %}
            <a class="btn btn-info btn-sm" style="background-color: blueviolet;" onclick="return confirm('Are you sure?');" href="{{ url_for('user.applytask', task_id=task.id) }}">Apply Task</a></br></br>
        {% endif %}
    {% endif %}
    
    <a class="button1" href="{{ url_for('tasks.mytasks') }}">Back to My Tasks</a>

{% endblock %}

movehelper/templates/tasks/taskedit.html
{% extends 'base2.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block content %}
<style>
    .button1:link, .button1:visited {   
        background-color: #474542;
        color: white;
        padding: 14px 25px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        margin-left: 10px;
        margin-top: 10px;
        font-weight: bold;
        font-family: "Times New Roman", Times, serif;
        border-radius: 8px;
    }

    .button1:hover, .button1:active {
        color: black;
        background-color: rgb(50, 90, 85);
    }
    body{
        background-image: url("https://prd-image-masters.caravan-stories.com.tw/c/sig=1.wJPHhERFgwnK6pqXcpnOuTgK_Pkdv2HcqqPh335P2iM=/caravan-stories/masters/production-tw/attachments/1b21c7fb435b583e0592c03c04df26a9.jpg");
        background-repeat: no-repeat;
        background-size: cover;       
    }


</style>

    <div class="jumbotron">
        <div class="row">
        
            <div class="col-md-4">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header"><h4>Update Your Task</h4></div>
                    <div class="card-body">
                        {{ render_form(form) }}
                        <hr>
                        
                    </div>
                </div>
            </div>

        </div>
        <a class="button1" href="{{ url_for('tasks.mytasks') }}">Back to My Tasks</a>
    </div>
    
    
{% endblock %}