movehelper/blueprints/auth.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login

from movehelper.config import Operations
from movehelper.emails import send_confirm_email, send_reset_password_email
from movehelper.forms.auth import RegisterForm, LoginForm, ForgetPasswordForm, ResetPasswordForm
from movehelper.models import UserAccount
from movehelper.tools import db
from movehelper.helpers import generate_token, validate_token

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = UserAccount.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.verify_password(form.pwd.data):
            if login_user(user, form.remember_me.data):
                flash('Login success.', 'info')
                return redirect(url_for('user.index'))
            else:
                flash('Your account is blocked.', 'warning')
                return redirect(url_for('main.index'))
        flash('Invalid email or password.', 'warning')
    return render_template('auth/login.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success!','info')
    return redirect(url_for('main.index'))

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))
    lastuser = UserAccount.query.order_by(UserAccount.id.desc()).first()
    if lastuser != None:
        id = int(lastuser.id)
    else:
        id = 100000
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data.lower()
        pwd = form.pwd.data
        newid = id + 1
        user = UserAccount(id=newid, username=username, email=email)
        user.create_password(pwd)
        db.session.add(user)
        db.session.commit()
        token = generate_token(user=user, operation='confirm')
        send_confirm_email(user=user, token=token)
        flash('Confirm email sent, check your inbox.', 'info')
        return redirect(url_for('main.index'))
    return render_template('auth/register.html', form=form)

@auth_bp.route('/confirm/<token>')
def confirm(token):
    if current_user.is_authenticated:
        if current_user.confirmed:
            flash('You are already comfirmed')
            return redirect(url_for('user.index'))

        if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
            flash('Account confirmed.', 'success')
            return redirect(url_for('user.index'))
        else:
            flash('Invalid or expired token.', 'danger')
            return redirect(url_for('.resend_confirm_email'))
    else:
        flash('Please login first!', 'warning')
        return redirect(url_for('main.index'))

@auth_bp.route('/resend-confirm-email')
@login_required
def resend_confirm_email():
    if current_user.confirmed:
        return redirect(url_for('user.index'))

    token = generate_token(user=current_user, operation=Operations.CONFIRM)
    send_confirm_email(user=current_user, token=token)
    flash('New email sent, check your inbox.', 'info')
    return redirect(url_for('user.index'))

@auth_bp.route('/forgetpassword', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))
    
    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = UserAccount.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash('Password reset email sent, check your emailbox.', 'info')
            return redirect(url_for('.login'))
        flash('Invalid email.', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/resetpassword.html', form=form)

@auth_bp.route('/resetpassword/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = UserAccount.query.filter_by(email=form.email.data.lower()).first()
        if user is None:
            flash('This account does not exist.', 'warning')
            return redirect(url_for('.reset_password', token=token))
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD,
                          new_password=form.pwd.data):
            flash('Password updated.', 'success')
            return redirect(url_for('.login'))
        else:
            flash('Invalid or expired link.', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/resetpassword.html', form=form)

movehelper/blueprints/tasks.py
from flask import render_template, flash, redirect, url_for, Blueprint, request, current_app
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login
from datetime import datetime
from sqlalchemy import join


from movehelper.config import Operations
from movehelper.emails import send_confirm_email
from movehelper.forms.tasks import NewTask
from movehelper.models import UserAccount, UserTasks, TaskOrders
from movehelper.tools import db
from movehelper.helpers import generate_token, validate_token
from movehelper.filter import confirm_required


tasks_bp = Blueprint('tasks', __name__)


@tasks_bp.route('/opentasks')
@login_required
def opentasks():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOVEHELPER_TASKS_PER_PAGE']
    pagination = UserTasks.query.filter(UserTasks.user_id!=current_user.id, UserTasks.status==False).order_by(UserTasks.pubtime.desc()).paginate(page, per_page=per_page)
    tasks = pagination.items
    return render_template('tasks/opentasks.html', pagination=pagination, tasks=tasks)


@tasks_bp.route('/new', methods=['GET', 'POST'])
@login_required
@confirm_required
def newtask():
    form = NewTask()
    if form.validate_on_submit():
        title = form.title.data
        context = form.context.data
        contact = form.contact.data
        location = form.location.data
        mpnum = form.manpower.data
        task = UserTasks(title=title, context=context, contact=contact, location=location, mpnum=mpnum, user_id=current_user.id )
        db.session.add(task)
        db.session.commit()
        flash('Task Created!', 'success')
        return redirect(url_for('user.index'))
    return render_template('tasks/newtask.html', form=form)

    
@tasks_bp.route('task/<int:task_id>', methods=['GET', 'POST'])
@login_required
@confirm_required
def taskdet(task_id):
    task = UserTasks.query.get_or_404(task_id)
    orders = TaskOrders.query.filter(TaskOrders.task_id==task_id).all()
    order = TaskOrders.query.filter(TaskOrders.task_id==task_id, TaskOrders.manpower==current_user.id).all()
    taskstatus = task.status
    return render_template('tasks/taskdet.html', task=task, taskstatus=taskstatus, orders=orders, order=order)
    

@tasks_bp.route('/mytasks', methods=['GET', 'POST'])
@login_required
@confirm_required
def mytasks():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOVEHELPER_TASKS_PER_PAGE']
    pagination = UserTasks.query.filter(UserTasks.user_id==current_user.id).order_by(UserTasks.pubtime.desc()).paginate(page, per_page=per_page)
    usertasks = pagination.items
    return render_template('tasks/mytasks.html', pagination=pagination, usertasks=usertasks)


@tasks_bp.route('/task/<int:task_id>/taskedit', methods=['GET', 'POST'])
@login_required
@confirm_required
def taskedit(task_id):
    form = NewTask()
    task = UserTasks.query.get_or_404(task_id)
    if form.validate_on_submit():
        task.title = form.title.data
        task.context = form.context.data
        task.contact = form.contact.data
        task.location = form.location.data
        task.mpnum = form.manpower.data
        db.session.commit()
        flash('Task Updated!','success')
        return redirect(url_for('tasks.taskdet', task_id=task.id))
    form.title.data = task.title
    form.context.data = task.context
    form.contact.data = task.contact
    form.location.data = task.location
    return render_template('tasks/taskedit.html', form=form, task=task)


@tasks_bp.route('/task/<int:task_id>/taskdelete', methods=['GET', 'POST'])
@login_required
@confirm_required
def taskdelete(task_id):
    task = UserTasks.query.get_or_404(task_id)
    db.session.delete(task)
    db.session.commit()
    flash ('Task Deleted!', 'success')
    return redirect(url_for('tasks.mytasks'))


@tasks_bp.route('/task/<int:task_id>/applieddet', methods=['GET', 'POST'])
@login_required
@confirm_required
def applieddet(task_id):
    task = UserTasks.query.get_or_404(task_id)
    applyers = TaskOrders.query.join(UserAccount, TaskOrders.manpower==UserAccount.id).\
            filter(TaskOrders.task_id==task_id).with_entities(TaskOrders.id, TaskOrders.createtime, UserAccount.fname,\
            UserAccount.mname, UserAccount.lname, UserAccount.gender, UserAccount.birth, UserAccount.onid, UserAccount.license)\
            .all()
    return render_template('tasks/orderdet.html', task=task, applyers=applyers)

movehelper/blueprints/user.py
from flask import flash, redirect, url_for, render_template, Blueprint, request, current_app
from flask_login import login_user, logout_user, login_required, current_user, login_fresh
from sqlalchemy import or_

from movehelper.emails import send_order_email, send_order_email_2
from movehelper.forms.user import Certification, PasswordChange
from movehelper.models import UserAccount, UserTasks, TaskOrders
from movehelper.tools import db
from movehelper.filter import confirm_required, certificate_required


user_bp = Blueprint('user', '__name__')


@user_bp.route('/')
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOVEHELPER_TASKS_PER_PAGE']
    pagination = UserTasks.query.filter(UserTasks.user_id!=current_user.id).order_by(UserTasks.pubtime.desc()).paginate(page, per_page=per_page)
    tasks = pagination.items
    return render_template('user/index.html', pagination=pagination, tasks=tasks)


@user_bp.route('/passwordchange', methods=['GET', 'POST'])
@login_required
def passwordchange():
    form = PasswordChange()
    if form.validate_on_submit():
        current_user.create_password(form.pwd.data)
        db.session.commit()
        flash('PasswordChange successed. Please re-Login', 'success')
        logout_user()
        return redirect(url_for('main.index'))
    return render_template('user/passwordchange.html', form=form)


@user_bp.route('/certificate', methods=['GET', 'POST'])
@login_required
@confirm_required
def certificate():
    user = UserAccount.query.get_or_404(current_user.id)
    if user.certificated == True :
        flash('You were already certificated!', 'warning')
        return redirect(url_for('user.index'))
    else :
        form = Certification()
        if form.validate_on_submit():
            current_user.fname = form.namef.data
            current_user.mname = form.namem.data
            current_user.lname = form.namel.data
            current_user.birth = form.birthday.data
            current_user.gender = form.gender.data
            current_user.phone = form.phone.data
            current_user.onid = form.onid.data
            current_user.license = form.license.data
            current_user.certificated = True
            db.session.commit()
            flash('Certification successed.', 'success')
            return redirect(url_for('user.index'))
        return render_template('user/certificate.html', form = form)


@user_bp.route('/applytask/<int:task_id>', methods=['GET', 'POST'])
@login_required
@confirm_required
@certificate_required
def applytask(task_id):
    task = UserTasks.query.get_or_404(task_id)
    if  task.status == False:
        if task.mpnume < (task.mpnum - 1): 
            neworder = TaskOrders(manpower=current_user.id, task_id=task_id)
            task.mpnume += 1
            db.session.add(neworder)
            db.session.commit()
            flash('You applied this task', 'success')
            return redirect(url_for('user.index'))
        else:
            neworder = TaskOrders(manpower=current_user.id, task_id=task_id)
            task.mpnume += 1
            task.status = True
            db.session.add(neworder)
            db.session.commit()
            announcer = UserAccount.query.get_or_404(task.user_id)
            applyers = TaskOrders.query.join(UserAccount, TaskOrders.manpower==UserAccount.id).\
                        filter(TaskOrders.task_id==task_id).with_entities(UserAccount.email,\
                        UserAccount.username).all()
            send_order_email(announcer=announcer, taskNo=task_id)
            send_order_email_2(applyers=applyers, taskNo=task_id)
            flash('You applied this task', 'success')
            return redirect(url_for('user.index'))
    else :  
        flash('This task was closed', 'warning')
        return redirect(url_for('tasks.taskdet', task_id=task.id))


@user_bp.route('/myapply', methods=['GET', 'POST'])
@login_required
@confirm_required
@certificate_required
def myapply():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MOVEHELPER_TASKS_PER_PAGE']
    pagination = UserTasks.query.join(TaskOrders).filter(TaskOrders.manpower==current_user.id).with_entities(TaskOrders.id, TaskOrders.task_id, UserTasks.title, TaskOrders.createtime).order_by(TaskOrders.createtime.desc()).paginate(page, per_page=per_page)
    applys = pagination.items
    return render_template('user/myapplys.html', pagination=pagination, applys=applys)

movehelper/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {{ bootstrap.load_css()}}
</head>
<body>
    <style>
        body {
        
            background-image: url("https://prd-image-masters.caravan-stories.com.tw/c/sig=1.wJPHhERFgwnK6pqXcpnOuTgK_Pkdv2HcqqPh335P2iM=/caravan-stories/masters/production-tw/attachments/1b21c7fb435b583e0592c03c04df26a9.jpg");
            background-repeat: no-repeat;
            background-size: cover;
        }
      
        .alert {
            left: 500px;
            text-align: center;
	        position: fixed;
            top: 0;
            width: 300px;
	        z-index: 100;
        }   
        nav a:link, nav a:visited {
            
            background-color: #cf8422;
            color: white;
            padding: 14px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            margin-left: 30px;
            font-weight: bold;
            font-family: "Times New Roman", Times, serif;
        }

        nav a:hover, nav a:active {
            color: black;
            background-color: red;
        }

    </style>
    {% for message in get_flashed_messages() %}
        <div class="alert">
            {{ message }}
        </div>
    {% endfor %}
    <nav>
        <a href="{{ url_for('main.index') }}">Back to Home Page</a>
    </nav>

    <main>
        {% block content %}{% endblock %}
    </main>

{% block scripts %}{% endblock %}
</body>
</html>

movehelper/templates/base2.html
<!DOCTYPE html>
<html>
<head>
    {{ bootstrap.load_css()}}
</head>
<body>
    <style>
        .dropbtn {
        background-color: #4CAF50;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
        cursor: pointer;
        font-family: "Comic Sans MS", cursive, sans-serif;
        }
        .dropbtn1 {
        background-color: rgb(233, 163, 14);
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
        cursor: pointer;
        font-family: "Comic Sans MS", cursive, sans-serif;
        }

        .dropdown {
        position: relative;
        display: inline-block;
        }


        .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        
        }


        .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        font-family: "Arial Black", Gadget, sans-serif;
        background-color:rgb(212, 212, 202) ;
        }


        .dropdown-content a:hover {background-color: #b8661b}


        .dropdown:hover .dropdown-content {
        display: block;
        }


        .dropdown:hover .dropbtn {
        background-color: #3e8e41;
        }    
        .dropbtn a:link {
        color:#FFFFFF;
        text-decoration:none;
        }
        .dropbtn a:visited {
        color:#FFFFFF;
        text-decoration:none;
        }
        .dropbtn a:hover {
        color:#FFFFFF;
        text-decoration:none;
        }
        .dropbtn a:active {
        color:#FFFFFF;
        text-decoration:none;
        }
        .dropbtn1 a:link {
        color:#FFFFFF;
        text-decoration:none;
        }
        .dropbtn1 a:visited {
        color:#FFFFFF;
        text-decoration:none;
        }
        .dropbtn1 a:hover {
        color:#FFFFFF;
        text-decoration:none;
        }
        .dropbtn1 a:active {
        color:#FFFFFF;
        text-decoration:none;
        }

        .alert {
            left: 500px;
            text-align: center;
            position: fixed;
            width: 300px;
	        top: 0;
	        z-index: 100;
        }

        h1{
            margin: 20px;
            color: rgb(238, 166, 31);
            font-family: verdana;
            font-size: 300%;
            color: rgb(226, 158, 12);
            text-shadow: 1px 1px 2px black, 0 0 25px rgb(202, 163, 33), 0 0 5px darkblue;
        }

        h2{
            margin: 20px;
            font-family: verdana;
            font-size: 200%;
            color: rgb(216, 182, 32);
        }

        div p{
        color: rgb(21, 24, 197);
        font-size: 13px;
        margin: 20px;
        font: italic bold 15px/30px Georgia, serif;
        }

        body {
            background-image: url("https://blog.appfolio.com/wp-content/uploads/2016/06/moving-out-1140x531.jpg");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center; 
        }

        
        
    </style>
    {% for message in get_flashed_messages() %}
        <div class="alert">
            {{ message }}
        </div>
    {% endfor %}
    <div class="dropdown" style="float:right;">
        <button class="dropbtn1"><a href="{{ url_for('auth.logout') }}">Logout</a></button>
    </div>
    <div class="dropdown" style="float:right;">
        <button class="dropbtn" style="background-color: rgb(19, 112, 233);">Tasks</button>
        <div class="dropdown-content">
            <a href="{{ url_for('tasks.mytasks')}}">My Tasks</a>
            <a href="{{ url_for('tasks.newtask') }}">Release Task</a>
            <a href="{{ url_for('tasks.opentasks') }}">Open Tasks</a>
            <a href="{{ url_for('user.myapply') }}">My Applied Tasks</a>
        </div>
    </div>
    <div class="dropdown" style="float:right;">
        <button class="dropbtn">My Account</button>
        <div class="dropdown-content">
            {% if current_user.confirmed %}
                {% if current_user.certificated %}
                    <p style="background-color: #4CAF50; color: #FFF;">User Status: Certificated</p>
                {% else %}
                    <p style="background-color: rgb(21, 162, 228); color: #FFF;">User Status: Confirmed</p>
                {% endif %}
            {% else %}
                <p style="background-color: rgb(223, 26, 26); color: #FFF;">User Status: Unconfirmed</p>
            {% endif %}
            <a href="{{ url_for('user.index') }}">My Home</a>
            <a href="{{ url_for('user.certificate') }}">Certification</a>
            <a href="{{ url_for('user.passwordchange') }}">Change Password</a>
            
        </div>
    </div>
    <main>
        {% block content %}{% endblock %}
    </main>

{% block scripts %}{% endblock %}
</body>
</html>

movehelper/templates/base3.html
<!DOCTYPE html>
<html>
<head>
    {{ bootstrap.load_css()}}
</head>
<body>
    <style>
        body {
            background-image: url("https://blog.appfolio.com/wp-content/uploads/2016/06/moving-out-1140x531.jpg");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center; 
            background-color: #73AD21;
        }
        h1{
            margin: 20px;
            color: rgb(238, 166, 31);
            font-family: verdana;
            font-size: 300%;
            color: white;
            text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;
        }
        .alert {
            left: 500px;
            text-align: center;
	        position: fixed;
            top: 0;
            width: 300px;
	        z-index: 100;
        } 
        a:link, a:visited {
            border-radius: 50%;
            margin: 20px;
            background-color: #69b446;
            color: rgb(32, 74, 209);
            padding: 14px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-family: "Arial Black", Gadget, sans-serif;
            font-size: 30px;
        }

        a:hover, a:active {
            background-color: rgb(233, 154, 37);
            transition: .5s;
            font-family: "Arial Black", Gadget, sans-serif;
        }
        div p{
        color: rgb(21, 24, 197);
        font-family: courier;
        font-size: 100%;
        padding: 10px;
        border: 2px solid #fa0;
        border-style: outset;
        margin: 20px;
        }
        div p1{
        color: rgb(71, 51, 14);
        font-family: courier;
        font-size: 120%;
        padding: 10px;
        border: 2px solid #fa0;
        border-style: outset;
        margin: 20px;
        }
  
    </style>
    {% for message in get_flashed_messages() %}
        <div class="alert">
            {{ message }}
        </div>
    {% endfor %}
    <main>
        {% block content %}{% endblock %}
    </main>

{% block scripts %}{% endblock %}
</body>
</html>

movehelper/templates/index.html
{% extends 'base3.html' %}

{% block content %}
    <h1>MoveHelper </h1>
    <div class="row">
        <div class="col-sm-8">
            
            {% if tasks %}
                {% for task in tasks %}
                    <p>
                        Title:&nbsp;&nbsp;{{ task.title }}&nbsp;&nbsp;|&nbsp;&nbsp;Released at:&nbsp;&nbsp;{{ task.pubtime }}
                    </p>
                    
                {% endfor %}
                <p1>
                    Login in to check the detail!
                </p1>
            {% else %}    
                <h4>Login and rlease new announcement!</h4>
            {% endif %}
        </div>
    </div>

    <a href="{{ url_for('auth.login') }}">Login</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{{ url_for('auth.register') }}">Register</a>
    
    
{% endblock %}

movehelper/templates/macros.html
{% macro form_field(field) %}
    {{ field.label }}<br>
    {% if field.flags.required %}
        {{ field(required='required', **kwargs) }}<br>
    {% else %}
        {{ field(**kwargs) }}<br>
    {% endif %}
    {% if field.errors %}
        {% for error in field.errors %}
            <small class="error">{{ error }}</small><br>
        {% endfor %}
    {% endif %}
{% endmacro %}